import { Creator, PaymentLog } from "./types";

export const INITIAL_CREATORS: Creator[] = [
  {
    id: "creator_1783344356063",
    name: "Tia",
    platformProfiles: [{ platform: "Instagram", handle: "@tomazintia", followers: 17000, avgViews: 15600 }],
    status: "Selected",
    moneySpent: 0,
    videosPosted: 0,
    totalViewsGenerated: 0,
    notes: "",
  },
  {
    id: "creator_1783344115978",
    name: "Mercedes Cava",
    platformProfiles: [{ platform: "Instagram", handle: "@mercedes.cava", followers: 48000, avgViews: 15000 }],
    status: "Selected",
    moneySpent: 0,
    videosPosted: 0,
    totalViewsGenerated: 0,
    notes: "",
  },
  {
    id: "creator_1783343894394",
    name: "Francois Pearce",
    platformProfiles: [{ platform: "Instagram", handle: "@walkwithfran", followers: 73000, avgViews: 68495 }],
    status: "Selected",
    moneySpent: 0,
    videosPosted: 0,
    totalViewsGenerated: 0,
    notes: "",
  },
  {
    id: "creator_1783343773273",
    name: "Tina Reistad",
    platformProfiles: [{ platform: "Instagram", handle: "@tinixadventure", followers: 32000, avgViews: 11700 }],
    status: "Selected",
    moneySpent: 0,
    videosPosted: 0,
    totalViewsGenerated: 0,
    notes: "",
  },
  {
    id: "creator_1783343656705",
    name: "James",
    platformProfiles: [{ platform: "Instagram", handle: "@jamesjourneys__", followers: 45000, avgViews: 11300 }],
    status: "Selected",
    moneySpent: 0,
    videosPosted: 0,
    totalViewsGenerated: 0,
    notes: "",
  },
  {
    id: "creator_1783343541422",
    name: "Ava",
    platformProfiles: [{ platform: "Instagram", handle: "@avafgrace", followers: 145000, avgViews: 411385 }],
    status: "Selected",
    moneySpent: 0,
    videosPosted: 0,
    totalViewsGenerated: 0,
    notes: "",
  },
  {
    id: "creator_1783343345187",
    name: "Wiktoria",
    platformProfiles: [{ platform: "Instagram", handle: "@wiktoriawanders", followers: 180000, avgViews: 120000 }],
    status: "Selected",
    moneySpent: 0,
    videosPosted: 0,
    totalViewsGenerated: 0,
    notes: "",
  },
  {
    id: "creator_1783343158488",
    name: "Stefany",
    platformProfiles: [{ platform: "Instagram", handle: "@soytraveler", followers: 34000, avgViews: 66529 }],
    status: "Selected",
    moneySpent: 0,
    videosPosted: 0,
    totalViewsGenerated: 0,
    notes: "really good",
  },
  {
    id: "creator_1783342943871",
    name: "Lucia",
    platformProfiles: [{ platform: "Instagram", handle: "@capturedbyluciah", followers: 39000, avgViews: 15000 }],
    status: "Selected",
    moneySpent: 0,
    videosPosted: 0,
    totalViewsGenerated: 0,
    notes: "really good candidate",
  },
  {
    id: "creator_1783342471679",
    name: "Emma",
    platformProfiles: [{ platform: "Instagram", handle: "@travel.withemmaa", followers: 6000, avgViews: 600 }],
    status: "Selected",
    moneySpent: 0,
    videosPosted: 0,
    totalViewsGenerated: 0,
    notes: "not much of an influencer",
  },
  {
    id: "creator_1783342202347",
    name: "Patrizia",
    platformProfiles: [{ platform: "Instagram", handle: "@patty_traveler", followers: 1000, avgViews: 1000 }],
    status: "Selected",
    moneySpent: 0,
    videosPosted: 0,
    totalViewsGenerated: 0,
    notes: "not much of an influencer, speaks italian (i think)",
  },
];

export const INITIAL_PAYMENTS: PaymentLog[] = [];
